#!/usr/bin/env ruby

%w[git
   gh
   coreutils
   ctags
   growlnotify
   libevent
   readline
   fzf
   ack
   tree
   vim
   tmux
   zsh
   rbenv
   ruby-build
   ripgrep
   node
   exa
   tldr
   bat
   jq].each { |item| system("brew install #{item}") }
