#!/usr/bin/env bash

if [ ! -x /usr/local/Cellar ]; then
  echo "Installing Brew..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  echo 'export PATH="/usr/local/bin:$PATH"' | tee -a ~/.bash_profile ~/.zshrc
fi
