#!/usr/bin/env bash

if [ ! -x /usr/local/Cellar ]; then
  echo "Installing Brew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  echo 'export PATH="/usr/local/bin:$PATH"' | tee -a ~/.bash_profile ~/.zshrc
fi
